params:
  epochs: 300
  device: cuda:0
  cutout_sizes: [2, 4, 8, 16]
  num_disjoint_masks: 3
  category: bottle
  height: 256
  width: 256
  cross_validation: 0
  batch_size: 4
  experiment_name: mvtec
  run_name: ${params.category}_cv${params.cross_validation}

model:
  name: riad.models - UNet
  args:

transforms:
  train:
  - name: albumentations - Resize
    args:
      height: ${params.height}
      width: ${params.width}
      p: 1
  - name: albumentations - Normalize
    args:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      p: 1
  - name: albumentations.pytorch - ToTensorV2
    args:
      p: 1
  val:
  - name: albumentations - Resize
    args:
      height: ${params.height}
      width: ${params.width}
      p: 1
  - name: albumentations - Normalize
    args:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      p: 1
  - name: albumentations.pytorch - ToTensorV2
    args:
      p: 1
  test:
  - name: albumentations - Resize
    args:
      height: ${params.height}
      width: ${params.width}
      p: 1
  - name: albumentations - Normalize
    args:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      p: 1
  - name: albumentations.pytorch - ToTensorV2
    args:
      p: 1

datasets:
  train:
    name: riad.datasets - MVTecDataset
    args:
      data_dir: /app/RIAD/data
      query_list:
      - cv${params.cross_validation}=='train' & category=='${params.category}'
      debug: False
  val:
    name: riad.datasets - MVTecDataset
    args:
      data_dir: /app/RIAD/data
      query_list:
      - cv${params.cross_validation}=='val' & category=='${params.category}'
      debug: False
  test:
    name: riad.datasets - MVTecDataset
    args:
      data_dir: /app/RIAD/data
      query_list:
      - cv${params.cross_validation}=='test' & category=='${params.category}'
      debug: false

dataloaders:
  train:
    name: torch.utils.data - DataLoader
    args:
      batch_size: ${params.batch_size}
      num_workers: ${params.batch_size}
      pin_memory: True
      shuffle: True
  val:
    name: torch.utils.data - DataLoader
    args:
      batch_size: ${params.batch_size}
      num_workers: ${params.batch_size}
      pin_memory: True
      shuffle: True
  test:
    name: torch.utils.data - DataLoader
    args:
      batch_size: ${params.batch_size}
      num_workers: ${params.batch_size}
      pin_memory: True
      shuffle: True

optimizer:
  name: torch.optim - Adam
  args:
    lr: 0.0001
    weight_decay: 0.00001

scheduler:
  name: torch.optim.lr_scheduler - CosineAnnealingWarmRestarts
  args:
    T_0: 10
    T_mult: 2
    eta_min: 0.0001
    last_epoch: -1

criterions:
  MSGMS:
    name: riad.criterions - MSGMSLoss
    args:
      num_scales: 4
  SSIM:
    name: riad.criterions - SSIMLoss
    args:
      kernel_size: 11
      sigma: 1.5
  MSE:
    name: torch.nn - MSELoss
    args:
      reduction: mean

early_stopping:
  name: riad.utils - EarlyStopping
  args:
    patience: 20
    delta: 0
